### ISSUE TITLE
Issue 3: User can view to-do's page

### ISSUE THREAD

**Issue by josh-tjiauw** [josh-tjiauw/travel-companion#3]
- [x] On the home page, add a button to navigate to the to-do's page.
- [x] Add a container div, home button in the navbar, and title component
- [x] Add an input for the user to enter a city name they want to go to in the future
- [x] Add new divs based on what the user puts
- [x] Add strikelines when a user has visited the place
- [x] Delete the div when user presses the x button
